# A simple example of the marching tetrahedron algorithm

In [8]:
# Use a 3x3x3 grid

import numpy as np

# Create a 3x3x3 grid of zeros
n = 3
c = 3.5
grid = np.zeros((n+1, n+1, n+1), dtype=float)

for k in range (0, n+1):
    for j in range (0, n+1):
        for i in range (0, n+1):
            grid[i,j,2] = 3.0
            grid[i,j,3] = 4.0

print(grid)



[[[0. 0. 3. 4.]
  [0. 0. 3. 4.]
  [0. 0. 3. 4.]
  [0. 0. 3. 4.]]

 [[0. 0. 3. 4.]
  [0. 0. 3. 4.]
  [0. 0. 3. 4.]
  [0. 0. 3. 4.]]

 [[0. 0. 3. 4.]
  [0. 0. 3. 4.]
  [0. 0. 3. 4.]
  [0. 0. 3. 4.]]

 [[0. 0. 3. 4.]
  [0. 0. 3. 4.]
  [0. 0. 3. 4.]
  [0. 0. 3. 4.]]]


In [54]:
# I have the position of each cube as (i,j,k) where i is the x position, j is the y position, and k is the z position
# I can compute the relative position with the following rule:
# i' = i if i is even, i' = i+1 else. Applies for j and k as well
# i'' = 2*i+1-i'. Applies for j and k as well

# Compute the (0,0,0) 

block_coordinate = (2,0,0)
point = 5 # From 1 to 8

if point < 1:
    raise ValueError("Number must be >= 1")

conversion_table = [ # Note that this pattern is the 0-7 in binary from right to left
    ("i'", "j'", "k'"),
    ("i''", "j'", "k'"),
    ("i'", "j''", "k'"),
    ("i''", "j''", "k'"),
    ("i'", "j'", "k''"),
    ("i''", "j'", "k''"),
    ("i'", "j''", "k''"),
    ("i''", "j''", "k''"),
]

# I want to find the 7th point of the block_coordinate = (0,0,0) cube

one_apex = np.zeros((3), dtype = int)
two_apex = np.zeros((3), dtype = int)
global_coordinate = np.zeros((3), dtype = int)
local_coordinate = np.zeros((3), dtype = int)

for var in range(3):
    if block_coordinate[var] % 2 == 0:
        one_apex[var] = block_coordinate[var]
    else:
        one_apex[var] = block_coordinate[var]+1
    
    two_apex[var] = 2*block_coordinate[var]+1-one_apex[var]

    if conversion_table[point-1][var] == "i'" or conversion_table[point-1][var] == "j'" or conversion_table[point-1][var] == "k'":
        global_coordinate[var] = one_apex[var]
    else:
        global_coordinate[var] = two_apex[var]
    local_coordinate[var] = global_coordinate[var]-block_coordinate[var]

    

print("Global coordinate of the block number", str(point), "with block position block_coordinate", str(block_coordinate), "in the global grid" )
print(global_coordinate)
print("The local coordinate within the block is at:" )
print(local_coordinate)

Global coordinate of the block number 5 with block position block_coordinate (2, 0, 0) in the global grid
[2 0 1]
The local coordinate within the block is at:
[0 0 1]


In [1]:
# Now I need the reverse, i.e.: from a coordinate I want to know the number among its block vertices
# For example. I know the the vertex 8 in the cube at location (2,1,0) is at position (3,1,1)

# Now, from (3,1,1) and (2,1,0) I want to go back to 8  

# There is this property for which if the sum of the block coordinates is even, the block has the normal configuration,
#   if odd then it's mirrored.
# I can first handle the first case. Example with 5 for (2,0,0) which is in (2,0,1)

global_coord_vertex = (3,2,2)
new_coord = np.zeros((3), dtype=int)
sum = 0

new_coord[0] = global_coord_vertex[0] % 2
new_coord[1] = global_coord_vertex[1] % 2
new_coord[2] = global_coord_vertex[2] % 2

print(new_coord)
new_coord = str(new_coord)

inv_conversion_table_1 = {
    "[0 0 0]": 1,
    "[1 0 0]": 2,
    "[0 1 0]": 3,
    "[1 1 0]": 4,
    "[0 0 1]": 5,
    "[1 0 1]": 6,
    "[0 1 1]": 7,
    "[1 1 1]": 8
}

# Once I know this is the normal disposition of the cube
print(inv_conversion_table_1[new_coord])

NameError: name 'np' is not defined