In [ ]:
import numpy as np
import matplotlib as plt

def from_point_globalcube_to_local_global_point(point, block_coordinate):
    """Get the global coordinate of a vertex by specifiyng the coordinate of the
    block that contain the vertex and the vertex index you want to know

    Args:
        point (int): point index
        block_coordinate (tuple): coordinates of the block

    Raises:
        ValueError: Index must be >0, <9

    Returns:
        list: local point coordinates
        list: global point coordinates
    """
    if point < 1 or point > 8:
        raise ValueError("Number must be > 0 and < 9")

    conversion_table = [ # Note that this pattern is the 0-7 in binary from right to left
        ("i'", "j'", "k'"),
        ("i''", "j'", "k'"),
        ("i'", "j''", "k'"),
        ("i''", "j''", "k'"),
        ("i'", "j'", "k''"),
        ("i''", "j'", "k''"),
        ("i'", "j''", "k''"),
        ("i''", "j''", "k''"),
    ]

    # I want to find the 7th point of the block_coordinate = (0,0,0) cube

    one_apex = np.zeros((3), dtype = int)
    two_apex = np.zeros((3), dtype = int)
    global_coordinate = np.zeros((3), dtype = int)
    local_coordinate = np.zeros((3), dtype = int)

    for var in range(3):
        if block_coordinate[var] % 2 == 0:
            one_apex[var] = block_coordinate[var]
        else:
            one_apex[var] = block_coordinate[var]+1
        
        two_apex[var] = 2*block_coordinate[var]+1-one_apex[var]

        if conversion_table[point-1][var] == "i'" or conversion_table[point-1][var] == "j'" or conversion_table[point-1][var] == "k'":
            global_coordinate[var] = one_apex[var]
        else:
            global_coordinate[var] = two_apex[var]
        local_coordinate[var] = global_coordinate[var]-block_coordinate[var]

    return local_coordinate, global_coordinate

cube_5_tetrahedra = [
    (4, 6, 7, 8),
    (1, 5, 6, 7),
    (1, 3, 4, 7),
    (1, 2, 4, 6),
    (1, 4, 6, 7),
]

In [23]:

for j in range(5):
    list_gl_coord = []
    for i in range(4):
        _, global_coord = from_point_globalcube_to_local_global_point(cube_5_tetrahedra[j][i], (2,0,0))
        list_gl_coord.append(global_coord)

    print(list_gl_coord)

    mat = np.zeros((4,4))

    for idx, coord in enumerate(list_gl_coord):
        mat[0, idx] = 1  # First column from 1 to 4
        mat[1:4, idx] = coord  # Remaining columns filled with elements of list_gl_coord

    print(mat)

    det = np.linalg.det(mat)
    print("Determinant of mat:", det)

[array([3, 1, 0]), array([3, 0, 1]), array([2, 1, 1]), array([3, 1, 1])]
[[1. 1. 1. 1.]
 [3. 3. 2. 3.]
 [1. 0. 1. 1.]
 [0. 1. 1. 1.]]
Determinant of mat: -1.0000000000000002
[array([2, 0, 0]), array([2, 0, 1]), array([3, 0, 1]), array([2, 1, 1])]
[[1. 1. 1. 1.]
 [2. 2. 3. 2.]
 [0. 0. 0. 1.]
 [0. 1. 1. 1.]]
Determinant of mat: 1.0
[array([2, 0, 0]), array([2, 1, 0]), array([3, 1, 0]), array([2, 1, 1])]
[[1. 1. 1. 1.]
 [2. 2. 3. 2.]
 [0. 1. 1. 1.]
 [0. 0. 0. 1.]]
Determinant of mat: -1.0
[array([2, 0, 0]), array([3, 0, 0]), array([3, 1, 0]), array([3, 0, 1])]
[[1. 1. 1. 1.]
 [2. 3. 3. 3.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Determinant of mat: 1.0
[array([2, 0, 0]), array([3, 1, 0]), array([3, 0, 1]), array([2, 1, 1])]
[[1. 1. 1. 1.]
 [2. 3. 3. 2.]
 [0. 1. 0. 1.]
 [0. 0. 1. 1.]]
Determinant of mat: -2.0
